version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./docker/mongo:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db


  springboot-app:
    image: your-springboot-app-image
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/
    depends_on:
      - mongodb

volumes:
  mongodb_data: